-- ALL THE TABLE YOU WILL HAVE TO CREATE INSIDE YOUR DATABASE ( DATABSE NAME SHOULD SAME AS DB.java ) --

CREATE TABLE  E_BOOK 
   (	CALLNO VARCHAR(1000), 
	NAME VARCHAR(1000), 
	AUTHOR VARCHAR(1000), 
	PUBLISHER VARCHAR(1000), 
	QUANTITY INT, 
	ISSUED INT, 
	 CONSTRAINT E_BOOK_PK PRIMARY KEY (CALLNO)
   );
/
CREATE TABLE  E_LIBRARIAN 
   (	ID INT, 
	NAME VARCHAR(1000), 
	PASSWORD VARCHAR(1000), 
	EMAIL VARCHAR(1000), 
	MOBILE INT, 
	 CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY (ID) 
   );
/
Note: ID must be generated through sequence in E_LIBRARIAN table.

CREATE TABLE  E_ISSUEBOOK 
   (	CALLNO VARCHAR(1000) NOT NULL, 
	STUDENTID VARCHAR(1000) NOT NULL, 
	STUDENTNAME VARCHAR(1000), 
	STUDENTMOBILE INT, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(1000)
   );
/


